# Generated by Django 4.0.1 on 2022-01-29 09:20

from django.db import migrations, models
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamil', models.CharField(max_length=30, validators=[testapp.models.validation_gmail])),
            ],
        ),
    ]
