# Generated by Django 4.0.1 on 2022-01-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_validmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relase_date', models.DateField()),
                ('hero_name', models.CharField(max_length=20)),
                ('heroine_name', models.CharField(max_length=20)),
                ('director_name', models.CharField(max_length=20)),
                ('movie_name', models.CharField(max_length=20)),
            ],
        ),
    ]
